"use client";
import { FormEvent, useEffect, useState } from "react";
import { apiRequest, getSession } from "@/lib/auth";
type Product = { id: number; name: string; price: number; stockQuantity: number };
export default function SupplierProductsPage() {
  const [products, setProducts] = useState<Product[]>([]); const [form, setForm] = useState({ companyId: "", categoryId: "", name: "", description: "", price: "", stockQuantity: "0" }); const [error, setError] = useState("");
  useEffect(() => { if (!getSession()) { window.location.assign("/auth/signin"); return; } apiRequest<Product[]>("/api/products").then(setProducts).catch(() => setProducts([])); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); try { const created = await apiRequest<Product>("/api/products", { method: "POST", body: JSON.stringify({ ...form, companyId: Number(form.companyId), categoryId: Number(form.categoryId), price: Number(form.price), stockQuantity: Number(form.stockQuantity) }) }); setProducts([created, ...products]); setForm({ ...form, name: "", description: "", price: "", stockQuantity: "0" }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to create product."); } }
  return <main className="min-h-screen bg-slate-50 px-6 py-12 dark:bg-neutral-950"><div className="mx-auto max-w-5xl"><h1 className="text-4xl font-bold text-slate-900 dark:text-slate-50">Manage products</h1><form onSubmit={submit} className="mt-8 grid gap-4 rounded-2xl bg-white p-6 shadow-sm dark:bg-neutral-900 sm:grid-cols-2"><p className="sm:col-span-2 text-sm text-slate-500">Use your company and category IDs from the API.</p>{error && <p className="sm:col-span-2 text-red-700">{error}</p>}{Object.keys(form).map((key) => <label className="field-label" key={key}>{key}<input type={key === "price" || key === "stockQuantity" || key.endsWith("Id") ? "number" : "text"} value={form[key as keyof typeof form]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} required={key !== "description"} className="form-input" /></label>)}<button className="rounded-lg bg-blue-600 px-5 py-3 font-semibold text-white">Add product</button></form><div className="mt-8 space-y-3">{products.map((product) => <div key={product.id} className="flex justify-between rounded-xl bg-white p-5 shadow-sm dark:bg-neutral-900"><span>{product.name}</span><span>${Number(product.price).toFixed(2)} · {product.stockQuantity} in stock</span></div>)}</div></div></main>;
}
