"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { apiRequest } from "@/lib/auth";

type Product = { id: number; name: string; description?: string; price: number; stockQuantity?: number; company?: { name: string; description?: string; email?: string; phone?: string; address?: string; website?: string; businessType?: string; city?: string; country?: string } };

export default function ProductDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  const [product, setProduct] = useState<Product | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { params.then(({ id }) => apiRequest<Product>(`/api/products/${id}`).then(setProduct).catch((reason) => setError(reason instanceof Error ? reason.message : "Unable to load product."))); }, [params]);
  if (error) return <main className="section-shell min-h-[60vh] py-20"><p role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p></main>;
  if (!product) return <main className="section-shell min-h-[60vh] py-20 text-[#668073]">Loading product...</main>;
  return <main className="section-shell min-h-[65vh] py-10"><Link href="/products" className="text-sm font-bold text-[#087a45]">← Back to marketplace</Link><div className="mt-7 grid border border-[#dfe7e0] bg-white md:grid-cols-[1.05fr_1fr]"><div className="min-h-[420px] bg-[url('https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1200&q=82')] bg-cover bg-center p-6"><span className="bg-white px-3 py-1 text-xs font-bold uppercase tracking-wider text-[#087a45]">Cambodian origin</span></div><div className="p-7 sm:p-10"><p className="eyebrow">Product details</p><h1 className="mt-3 text-4xl font-extrabold leading-tight text-[#173d2c]">{product.name}</h1><p className="mt-5 leading-7 text-[#668073]">{product.description}</p><div className="mt-7 grid grid-cols-2 border-y border-[#e5e9e6] py-5"><div><p className="text-xs uppercase tracking-wider text-[#789080]">Price</p><p className="mt-1 text-2xl font-bold text-[#173d2c]">${Number(product.price).toFixed(2)}</p></div><div><p className="text-xs uppercase tracking-wider text-[#789080]">Availability</p><p className="mt-1 font-bold text-[#087a45]">{product.stockQuantity ?? 0} units</p></div></div>{product.company && <section className="mt-7 border-t border-[#e5e9e6] pt-6"><p className="text-xs font-bold uppercase tracking-widest text-[#087a45]">Supplier</p><h2 className="mt-2 text-lg font-bold text-[#173d2c]">{product.company.name}</h2>{product.company.businessType && <p className="text-sm text-[#668073]">{product.company.businessType}</p>}{product.company.description && <p className="mt-3 text-sm leading-6 text-[#668073]">{product.company.description}</p>}<p className="mt-3 text-sm text-[#789080]">{[product.company.city, product.company.country].filter(Boolean).join(", ")}</p>{product.company.website && <a className="mt-2 block text-sm font-semibold text-[#087a45] hover:underline" href={product.company.website} target="_blank" rel="noreferrer">{product.company.website}</a>}</section>}<Link href={`/rfqs/new?productId=${product.id}`} className="mt-8 inline-block bg-[#0b5d3b] px-6 py-3.5 font-semibold text-white hover:bg-[#087a45]">Request a quote <span aria-hidden>→</span></Link></div></div></main>;
}
