create table if not exists categories (id bigserial primary key,name varchar(255) not null unique,description text,active boolean not null default true,created_at timestamp not null default current_timestamp,updated_at timestamp);
create table if not exists product_images (id bigserial primary key,product_id bigint not null references products(id) on delete cascade,image_url varchar(1000) not null,created_at timestamp not null default current_timestamp);
create table if not exists rfqs (id bigserial primary key,buyer_id bigint not null references users(id),title varchar(255) not null,description text,status varchar(30) not null default 'OPEN',expires_at timestamp,created_at timestamp not null default current_timestamp);
create table if not exists rfq_items (id bigserial primary key,rfq_id bigint not null references rfqs(id) on delete cascade,product_id bigint not null references products(id),quantity integer not null check(quantity>0),target_price numeric(19,2));
create table if not exists quotations (id bigserial primary key,rfq_id bigint not null references rfqs(id),supplier_id bigint not null references users(id),total_amount numeric(19,2) not null,status varchar(30) not null default 'SUBMITTED',notes text,created_at timestamp not null default current_timestamp);
create table if not exists quotation_items (id bigserial primary key,quotation_id bigint not null references quotations(id) on delete cascade,product_id bigint not null references products(id),quantity integer not null check(quantity>0),unit_price numeric(19,2) not null);
create table if not exists orders (id bigserial primary key,buyer_id bigint not null references users(id),supplier_id bigint not null references users(id),quotation_id bigint not null unique references quotations(id),total_amount numeric(19,2) not null,status varchar(30) not null default 'PENDING',created_at timestamp not null default current_timestamp,updated_at timestamp);
create table if not exists order_items (id bigserial primary key,order_id bigint not null references orders(id) on delete cascade,product_id bigint not null references products(id),quantity integer not null check(quantity>0),unit_price numeric(19,2) not null);
create index if not exists idx_rfqs_buyer on rfqs(buyer_id); create index if not exists idx_quotations_rfq on quotations(rfq_id); create index if not exists idx_quotations_supplier on quotations(supplier_id); create index if not exists idx_orders_buyer on orders(buyer_id); create index if not exists idx_orders_supplier on orders(supplier_id);
