"use client";
import { useEffect, useState } from "react";
import { apiRequest, getSession } from "@/lib/auth";
type Rfq = { id: number; title: string; description?: string; items?: { productId: number; quantity: number }[] };
export default function QuotationsPage() {
  const [rfqs, setRfqs] = useState<Rfq[]>([]); const [error, setError] = useState(""); const [selected, setSelected] = useState<number | null>(null); const [price, setPrice] = useState(""); const [shippingCost, setShippingCost] = useState(""); const [deliveryDate, setDeliveryDate] = useState(""); const [sent, setSent] = useState("");
  useEffect(() => { if (!getSession()) { window.location.assign("/auth/signin"); return; } apiRequest<Rfq[]>("/api/rfqs/open").then(setRfqs).catch((reason) => setError(reason instanceof Error ? reason.message : "Unable to load RFQs.")); }, []);
  async function submit(rfq: Rfq) {
    const item = rfq.items?.[0]; if (!item) return;
    try { await apiRequest("/api/quotations", { method: "POST", body: JSON.stringify({ rfqId: rfq.id, notes: "", shippingCost: Number(shippingCost), deliveryDate, items: [{ productId: item.productId, quantity: item.quantity, unitPrice: Number(price) }] }) }); setSent(`Quotation sent for "${rfq.title}".`); setSelected(null); setPrice(""); setShippingCost(""); setDeliveryDate(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to send quotation."); }
  }
  return <main className="workspace-page"><div className="section-shell"><div className="workspace-heading"><div><p className="eyebrow">Supplier workspace / Opportunities</p><h1 className="workspace-title">Buyer requests, ready for your offer.</h1><p className="workspace-lede">Review open RFQs and send a clear quotation directly to buyers.</p></div><span className="count-badge">{rfqs.length} open</span></div>{sent && <p role="status" className="form-notice form-success">{sent}</p>}{error && <p role="alert" className="form-notice form-error">{error}</p>}<div className="rfq-list">{rfqs.map((rfq) => <article key={rfq.id} className="rfq-card"><div className="rfq-card-top"><div><span className="rfq-label">Request #{rfq.id}</span><h2>{rfq.title}</h2></div><span className="status-pill status-open">Open</span></div><p className="rfq-description">{rfq.description || "The buyer has not added additional notes."}</p><p className="rfq-items">{rfq.items?.map((item) => `${item.productId} × ${item.quantity} units`).join(", ") || "See request details"}</p>{selected === rfq.id ? <div className="quotation-form"><label className="field-label">Unit price<input type="number" min="0" step="0.01" value={price} onChange={(event) => setPrice(event.target.value)} className="form-input" /></label><label className="field-label">Shipping cost<input type="number" min="0" step="0.01" value={shippingCost} onChange={(event) => setShippingCost(event.target.value)} className="form-input" /></label><label className="field-label">Delivery date<input type="date" value={deliveryDate} onChange={(event) => setDeliveryDate(event.target.value)} className="form-input" /></label><div className="quotation-actions"><button onClick={() => submit(rfq)} disabled={!price || !shippingCost || !deliveryDate} className="workspace-primary">Send quotation <span>→</span></button><button onClick={() => setSelected(null)} className="cancel-button">Cancel</button></div></div> : <button onClick={() => { setSelected(rfq.id); setError(""); }} className="workspace-secondary">Prepare quotation <span>→</span></button>}</article>)}</div>{!error && rfqs.length === 0 && <div className="empty-state"><h2>No open RFQs yet</h2><p>New buyer requests will appear here when they are ready for supplier offers.</p></div>}</div></main>;
}
