"use client";
import { useEffect, useState } from "react";
import { apiRequest, getSession } from "@/lib/auth";
type Rfq = { id: number; title: string; description?: string; items?: { productId: number; quantity: number }[] };
export default function QuotationsPage() {
  const [rfqs, setRfqs] = useState<Rfq[]>([]); const [error, setError] = useState(""); const [selected, setSelected] = useState<number | null>(null); const [price, setPrice] = useState(""); const [sent, setSent] = useState("");
  useEffect(() => { if (!getSession()) { window.location.assign("/auth/signin"); return; } apiRequest<Rfq[]>("/api/rfqs/open").then(setRfqs).catch((reason) => setError(reason instanceof Error ? reason.message : "Unable to load RFQs.")); }, []);
  async function submit(rfq: Rfq) {
    const item = rfq.items?.[0]; if (!item) return;
    try { await apiRequest("/api/quotations", { method: "POST", body: JSON.stringify({ rfqId: rfq.id, notes: "", items: [{ productId: item.productId, quantity: item.quantity, unitPrice: Number(price) }] }) }); setSent(`Quotation sent for "${rfq.title}".`); setSelected(null); setPrice(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to send quotation."); }
  }
  return <main className="min-h-screen bg-slate-50 px-6 py-12 dark:bg-neutral-950"><div className="mx-auto max-w-5xl"><h1 className="text-4xl font-bold text-slate-900 dark:text-slate-50">Buyer RFQs</h1><p className="mt-2 text-slate-600 dark:text-slate-400">Open requests waiting for your quotation.</p>{sent && <p role="status" className="mt-6 rounded-lg bg-green-50 p-3 text-green-700">{sent}</p>}{error && <p role="alert" className="mt-6 text-red-700">{error}</p>}<div className="mt-8 space-y-4">{rfqs.map((rfq) => <article key={rfq.id} className="rounded-2xl bg-white p-6 shadow-sm dark:bg-neutral-900"><h2 className="text-xl font-semibold">{rfq.title}</h2><p className="mt-2 text-sm text-slate-500">{rfq.description}</p><p className="mt-4 text-sm">Items: {rfq.items?.map((item) => `${item.productId} × ${item.quantity}`).join(", ") || "See RFQ details"}</p>{selected === rfq.id ? <div className="mt-5 flex flex-wrap items-end gap-3"><label className="field-label">Unit price<input type="number" min="0" step="0.01" value={price} onChange={(event) => setPrice(event.target.value)} className="form-input" /></label><button onClick={() => submit(rfq)} disabled={!price} className="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white disabled:opacity-50">Send quotation</button></div> : <button onClick={() => { setSelected(rfq.id); setError(""); }} className="mt-5 rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white">Prepare quotation</button>}</article>)}</div>{!error && rfqs.length === 0 && <p className="mt-10 text-slate-500">No open RFQs.</p>}</div></main>;
}
