"use client";
import { FormEvent, useEffect, useState } from "react";
import { apiRequest, getSession } from "@/lib/auth";
type Company = { id: number; name: string; description?: string; email?: string; phone?: string; address?: string; website?: string; businessType?: string; country: string; city: string };
const empty = { name: "", description: "", email: "", phone: "", address: "", website: "", businessType: "", country: "", city: "" };
export default function CompanyPage() {
  const [company, setCompany] = useState<Company | null>(null); const [form, setForm] = useState(empty); const [error, setError] = useState(""); const [saved, setSaved] = useState("");
  useEffect(() => { if (!getSession()) { window.location.assign("/auth/signin"); return; } apiRequest<Company[]>("/api/companies").then((items) => { const item = items[0]; if (item) { setCompany(item); setForm({ ...empty, ...item }); } }).catch((reason) => setError(reason instanceof Error ? reason.message : "Unable to load company.")); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setSaved(""); try { const value = await apiRequest<Company>(company ? `/api/companies/${company.id}` : "/api/companies", { method: company ? "PUT" : "POST", body: JSON.stringify(form) }); setCompany(value); setForm({ ...empty, ...value }); setSaved("Company profile saved."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save company."); } }
  async function remove() { if (!company || !window.confirm("Delete this company profile?")) return; setError(""); try { await apiRequest(`/api/companies/${company.id}`, { method: "DELETE" }); setCompany(null); setForm(empty); setSaved("Company profile deleted."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to delete company."); } }
  return <main className="workspace-page"><div className="section-shell"><div className="workspace-heading"><div><p className="eyebrow">Supplier workspace / Company</p><h1 className="workspace-title">Your company, clearly presented.</h1><p className="workspace-lede">Give buyers the information they need to understand your business and start a conversation.</p></div><span className={`status-pill ${company ? "status-complete" : ""}`}>{company ? "Profile saved" : "New profile"}</span></div><form onSubmit={submit} className="supplier-form">{saved && <p role="status" className="form-notice form-success">{saved}</p>}{error && <p role="alert" className="form-notice form-error">{error}</p>}<div className="form-section"><div><p className="form-section-number">01</p><h2>Business identity</h2><p>Start with the details buyers will see first.</p></div><div className="form-fields">{(["name", "businessType", "description"] as const).map((key) => <label className={`field-label ${key === "description" ? "field-wide" : ""}`} key={key}>{key === "businessType" ? "Business type" : key === "name" ? "Company name" : "About your business"}{key === "description" ? <textarea rows={4} value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} className="form-input" placeholder="What do you produce, process, or export?" /> : <input value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} required={key === "name"} className="form-input" placeholder={key === "name" ? "e.g. Mekong Harvest Co." : "e.g. Agriculture & export"} />}</label>)}</div></div><div className="form-section"><div><p className="form-section-number">02</p><h2>Location & contact</h2><p>Help buyers know where and how to reach you.</p></div><div className="form-fields">{(["country", "city", "email", "phone", "address", "website"] as const).map((key) => <label className="field-label" key={key}>{key[0].toUpperCase() + key.slice(1)}<input type={key === "website" ? "url" : key === "email" ? "email" : "text"} value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} required={key === "country" || key === "city"} className="form-input" placeholder={key === "website" ? "https://" : ""} /></label>)}</div></div><div className="form-actions"><button className="workspace-primary">Save profile <span>→</span></button>{company && <button type="button" onClick={remove} className="delete-button">Delete profile</button>}</div></form></div></main>;
}
