"use client";
import { FormEvent, useEffect, useState } from "react";
import { apiRequest, getSession } from "@/lib/auth";
type Company = { id: number; name: string; description?: string; email?: string; phone?: string; address?: string; country: string; city: string };
const empty = { name: "", description: "", email: "", phone: "", address: "", country: "", city: "" };
export default function CompanyPage() {
  const [company, setCompany] = useState<Company | null>(null); const [form, setForm] = useState(empty); const [error, setError] = useState(""); const [saved, setSaved] = useState("");
  useEffect(() => { if (!getSession()) { window.location.assign("/auth/signin"); return; } apiRequest<Company[]>("/api/companies").then((items) => { const item = items[0]; if (item) { setCompany(item); setForm({ ...empty, ...item }); } }).catch((reason) => setError(reason instanceof Error ? reason.message : "Unable to load company.")); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setSaved(""); try { const value = await apiRequest<Company>(company ? `/api/companies/${company.id}` : "/api/companies", { method: company ? "PUT" : "POST", body: JSON.stringify(form) }); setCompany(value); setForm({ ...empty, ...value }); setSaved("Company profile saved."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save company."); } }
  return <main className="min-h-screen bg-slate-50 px-6 py-12 dark:bg-neutral-950"><div className="mx-auto max-w-3xl"><h1 className="text-4xl font-bold text-slate-900 dark:text-slate-50">Company profile</h1><form onSubmit={submit} className="mt-8 grid gap-5 rounded-2xl bg-white p-6 shadow-sm dark:bg-neutral-900 sm:grid-cols-2">{saved && <p className="sm:col-span-2 rounded-lg bg-green-50 p-3 text-green-700">{saved}</p>}{error && <p className="sm:col-span-2 rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}{Object.keys(form).map((key) => <label className="field-label" key={key}>{key.replace(/^\w/, (c) => c.toUpperCase())}<input value={form[key as keyof typeof form]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} required={key === "name" || key === "country" || key === "city"} className="form-input" /></label>)}<button className="rounded-lg bg-blue-600 px-5 py-3 font-semibold text-white">Save company</button></form></div></main>;
}
